apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashes-deployment
  namespace: hashes
  labels:
    app: hashes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hashes
  template:
    metadata:
      labels:
        app: hashes
    spec:
      containers:
        - name: hashes
          image: yykhomenko/hashes:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hashes-configmap
            - secretRef:
                name: hashes-secret
          resources:
            requests:
              cpu: "200m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "150Mi"
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 11
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 1
